---
name: mx_env
description: A new Flutter plugin.
version: 3.1.0+1
author: 
homepage: 
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  package_info_plus: ^1.2.1
  shared_preferences: ^2.0.7
dev_dependencies:
  build_runner: "^2.1.2"
flutter:
  plugin:
    androidPackage: com.i2xc.mx_env
    pluginClass: MxEnvPlugin
#  assets:
#  - assets/jsons/
publish_to: none
